import ExcelJS from "exceljs";

// Native blob download — no file-saver dependency needed
function saveAs(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

const FONT_NAME = "Times New Roman";
const HEADER_FILL: ExcelJS.Fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD6E4F0" } };
const TITLE_FILL: ExcelJS.Fill  = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E2D3B" } };
const GREEN_FILL: ExcelJS.Fill  = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD4EDDA" } };
const RED_FILL: ExcelJS.Fill    = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8D7DA" } };
const AMBER_FILL: ExcelJS.Fill  = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFFF3CD" } };

function baseFont(bold = false, size = 11, color = "FF000000"): Partial<ExcelJS.Font> {
  return { name: FONT_NAME, bold, size, color: { argb: color } };
}

function applyHeaderRow(row: ExcelJS.Row, bgFill = HEADER_FILL) {
  row.eachCell((cell) => {
    cell.font = baseFont(true, 11);
    cell.fill = bgFill;
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    cell.border = {
      top: { style: "thin" }, bottom: { style: "thin" },
      left: { style: "thin" }, right: { style: "thin" },
    };
  });
  row.height = 22;
}

function autoWidth(sheet: ExcelJS.Worksheet, minWidth = 12, maxWidth = 50) {
  sheet.columns.forEach((col) => {
    let max = minWidth;
    col.eachCell?.({ includeEmpty: false }, (cell) => {
      const len = cell.value ? String(cell.value).length : 0;
      if (len > max) max = len;
    });
    col.width = Math.min(max + 4, maxWidth);
  });
}

function freezeAndFilter(sheet: ExcelJS.Worksheet, headerRow = 1) {
  sheet.views = [{ state: "frozen", ySplit: headerRow }];
  sheet.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: headerRow, column: sheet.columnCount } };
}

function addTitleBlock(sheet: ExcelJS.Worksheet, title: string, subtitle: string, colCount: number) {
  sheet.mergeCells(1, 1, 1, colCount);
  const t = sheet.getCell("A1");
  t.value = title;
  t.font = baseFont(true, 16, "FFFFFFFF");
  t.fill = TITLE_FILL;
  t.alignment = { horizontal: "center", vertical: "middle" };
  sheet.getRow(1).height = 30;

  sheet.mergeCells(2, 1, 2, colCount);
  const s = sheet.getCell("A2");
  s.value = subtitle;
  s.font = baseFont(false, 10, "FF888888");
  s.alignment = { horizontal: "center" };
  sheet.getRow(2).height = 16;
}

function addMetadataSheet(wb: ExcelJS.Workbook, generatedBy: string, totalRecords: number) {
  const sheet = wb.addWorksheet("Metadata");
  addTitleBlock(sheet, "REPORT METADATA", "System-generated information", 2);

  const rows = [
    ["Field", "Value"],
    ["Generated Date", new Date().toLocaleString("en-IN")],
    ["Generated By", generatedBy],
    ["Total Records", totalRecords],
    ["System Version", "Trackify v1.0"],
    ["Export Format", "XLSX (ExcelJS)"],
    ["Society", "Greenwood Heights Co-operative Housing Society"],
  ];

  rows.forEach((r, i) => {
    const row = sheet.addRow(r);
    if (i === 0) {
      applyHeaderRow(row);
    } else {
      row.getCell(1).font = baseFont(true, 11);
      row.getCell(2).font = baseFont(false, 11);
      row.eachCell((c) => {
        c.border = { top: { style: "thin" }, bottom: { style: "thin" }, left: { style: "thin" }, right: { style: "thin" } };
      });
    }
  });

  autoWidth(sheet);
  sheet.views = [{ state: "frozen", ySplit: 3 }];
}

// ── VISITOR PASS EXPORT ───────────────────────────────────────────────────────

export async function exportVisitorPassExcel(passes: any[], generatedBy = "Admin") {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Trackify";
  wb.created = new Date();

  // ── Raw Data ──
  const raw = wb.addWorksheet("Raw Data");
  addTitleBlock(raw, "VISITOR PASS REPORT", `Generated: ${new Date().toLocaleDateString("en-IN")}`, 7);
  raw.addRow([]);

  const headers = ["Visitor Name", "Flat No.", "Purpose", "Status", "Entry Time", "Exit Time", "Created At"];
  const hRow = raw.addRow(headers);
  applyHeaderRow(hRow);

  passes.forEach((p) => {
    const row = raw.addRow([
      p.visitor_name || "",
      p.flat_number || "",
      p.purpose || "",
      p.status || "",
      p.entry_time ? new Date(p.entry_time).toLocaleString("en-IN") : "—",
      p.exit_time  ? new Date(p.exit_time).toLocaleString("en-IN")  : "—",
      p.created_at ? new Date(p.created_at).toLocaleDateString("en-IN") : "",
    ]);
    row.eachCell((c) => { c.font = baseFont(false, 11); c.alignment = { vertical: "middle" }; });

    // Conditional formatting by status
    const statusCell = row.getCell(4);
    if (p.status === "exited")    { statusCell.fill = GREEN_FILL; statusCell.font = baseFont(true, 11, "FF155724"); }
    else if (p.status === "inside")   { statusCell.fill = AMBER_FILL; statusCell.font = baseFont(true, 11, "FF856404"); }
    else if (p.status === "expired" || p.status === "cancelled") { statusCell.fill = RED_FILL; statusCell.font = baseFont(true, 11, "FF721C24"); }
  });

  autoWidth(raw);
  freezeAndFilter(raw, 4);

  // ── Summary ──
  const sum = wb.addWorksheet("Summary");
  addTitleBlock(sum, "VISITOR SUMMARY", "", 3);
  sum.addRow([]);

  const statusCounts: Record<string, number> = {};
  const dayCounts: Record<string, number> = {};
  const hourCounts: Record<number, number> = {};

  passes.forEach((p) => {
    statusCounts[p.status] = (statusCounts[p.status] || 0) + 1;
    const day = p.created_at ? new Date(p.created_at).toLocaleDateString("en-IN") : "Unknown";
    dayCounts[day] = (dayCounts[day] || 0) + 1;
    if (p.entry_time) {
      const h = new Date(p.entry_time).getHours();
      hourCounts[h] = (hourCounts[h] || 0) + 1;
    }
  });

  const peakDay = Object.entries(dayCounts).sort((a, b) => b[1] - a[1])[0];
  const peakHour = Object.entries(hourCounts).sort((a, b) => Number(b[1]) - Number(a[1]))[0];

  const summaryRows = [
    ["Metric", "Value", "Notes"],
    ["Total Passes", passes.length, "All time"],
    ["Active", statusCounts["active"] || 0, "Pending entry"],
    ["Inside", statusCounts["inside"] || 0, "Currently inside"],
    ["Exited", statusCounts["exited"] || 0, "Completed visits"],
    ["Expired", statusCounts["expired"] || 0, ""],
    ["Cancelled", statusCounts["cancelled"] || 0, ""],
    ["Peak Day", peakDay?.[0] || "N/A", `${peakDay?.[1] || 0} visitors`],
    ["Peak Hour", peakHour ? `${peakHour[0]}:00 – ${Number(peakHour[0]) + 1}:00` : "N/A", `${peakHour?.[1] || 0} entries`],
  ];

  summaryRows.forEach((r, i) => {
    const row = sum.addRow(r);
    if (i === 0) { applyHeaderRow(row); }
    else {
      row.getCell(1).font = baseFont(true, 11);
      row.getCell(2).font = baseFont(false, 11);
      row.getCell(3).font = baseFont(false, 10, "FF888888");
    }
  });

  autoWidth(sum);
  sum.views = [{ state: "frozen", ySplit: 4 }];

  // ── Dashboard ──
  const dash = wb.addWorksheet("Dashboard");
  addTitleBlock(dash, "VISITOR DASHBOARD", "Charts & Visual Summary", 4);
  dash.addRow([]);

  // Visitors per day table (for chart data)
  dash.addRow(["Date", "Visitor Count"]);
  applyHeaderRow(dash.getRow(dash.rowCount));
  Object.entries(dayCounts).sort().forEach(([d, c]) => {
    dash.addRow([d, c]);
  });

  dash.addRow([]);
  dash.addRow(["Status", "Count"]);
  applyHeaderRow(dash.getRow(dash.rowCount));
  Object.entries(statusCounts).forEach(([s, c]) => {
    dash.addRow([s, c]);
  });

  autoWidth(dash);
  dash.views = [{ state: "frozen", ySplit: 4 }];

  // ── Insights ──
  const ins = wb.addWorksheet("Insights");
  addTitleBlock(ins, "AI INSIGHTS", "Auto-generated observations", 2);
  ins.addRow([]);

  const insightRows = [
    ["#", "Insight"],
    ["1", peakDay ? `Highest visitor traffic observed on ${peakDay[0]} (${peakDay[1]} visitors)` : "Insufficient data for peak day analysis"],
    ["2", peakHour ? `Most entries happen during ${peakHour[0]}:00 – ${Number(peakHour[0]) + 1}:00` : "No entry time data available"],
    ["3", `${((statusCounts["exited"] || 0) / Math.max(passes.length, 1) * 100).toFixed(1)}% of visitors have completed their visit (exited)`],
    ["4", `${statusCounts["cancelled"] || 0} passes were cancelled before use`],
    ["5", `Top 3 purposes: ${Object.entries(passes.reduce((acc: any, p) => { acc[p.purpose] = (acc[p.purpose] || 0) + 1; return acc; }, {})).sort((a: any, b: any) => b[1] - a[1]).slice(0, 3).map((e: any) => e[0]).join(", ")}`],
  ];

  insightRows.forEach((r, i) => {
    const row = ins.addRow(r);
    if (i === 0) { applyHeaderRow(row); }
    else {
      row.getCell(1).font = baseFont(true, 11);
      row.getCell(2).font = baseFont(false, 11);
      row.height = 20;
    }
  });

  autoWidth(ins);
  ins.views = [{ state: "frozen", ySplit: 4 }];

  // ── Metadata ──
  addMetadataSheet(wb, generatedBy, passes.length);

  const buf = await wb.xlsx.writeBuffer();
  saveAs(new Blob([buf]), `Visitor_Report_${new Date().toISOString().split("T")[0]}.xlsx`);
}

// ── SOCIETY FUND EXPORT ───────────────────────────────────────────────────────

export async function exportSocietyFundExcel(transactions: any[], budget: number, generatedBy = "Admin") {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Trackify";
  wb.created = new Date();

  // ── Raw Data ──
  const raw = wb.addWorksheet("Raw Data");
  addTitleBlock(raw, "SOCIETY FUND REPORT", `Generated: ${new Date().toLocaleDateString("en-IN")}`, 8);
  raw.addRow([]);

  const headers = ["Date", "Title", "Category", "Type", "Debit (Rs.)", "Credit (Rs.)", "Running Balance (Rs.)", "Status"];
  const hRow = raw.addRow(headers);
  applyHeaderRow(hRow);

  // Sort by date ascending for running balance
  const sorted = [...transactions].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
  let running = 0;

  sorted.forEach((tx) => {
    const debit  = tx.type === "debit"  ? tx.amount : 0;
    const credit = tx.type === "credit" ? tx.amount : 0;
    running += credit - debit;

    const row = raw.addRow([
      tx.date || "",
      tx.title || "",
      tx.category || "",
      tx.type === "credit" ? "Credit" : "Debit",
      debit  || "",
      credit || "",
      running,
      tx.status || "",
    ]);

    row.eachCell((c) => { c.font = baseFont(false, 11); c.alignment = { vertical: "middle" }; });

    // Color debit red, credit green
    if (tx.type === "debit") {
      row.getCell(5).font = baseFont(true, 11, "FF721C24");
      row.getCell(5).fill = RED_FILL;
    } else {
      row.getCell(6).font = baseFont(true, 11, "FF155724");
      row.getCell(6).fill = GREEN_FILL;
    }

    // Running balance color
    const balCell = row.getCell(7);
    balCell.font = baseFont(true, 11, running >= 0 ? "FF155724" : "FF721C24");
    balCell.fill = running >= 0 ? GREEN_FILL : RED_FILL;

    // Status color
    const stCell = row.getCell(8);
    if (tx.status === "Approved") { stCell.fill = GREEN_FILL; stCell.font = baseFont(false, 11, "FF155724"); }
    else { stCell.fill = AMBER_FILL; stCell.font = baseFont(false, 11, "FF856404"); }
  });

  autoWidth(raw);
  freezeAndFilter(raw, 4);

  // ── Summary ──
  const sum = wb.addWorksheet("Summary");
  addTitleBlock(sum, "FUND SUMMARY", "", 3);
  sum.addRow([]);

  const totalCredits = transactions.filter(t => t.type === "credit").reduce((s, t) => s + t.amount, 0);
  const totalDebits  = transactions.filter(t => t.type === "debit").reduce((s, t) => s + t.amount, 0);
  const balance = totalCredits - totalDebits;

  // Monthly breakdown
  const monthly: Record<string, { credit: number; debit: number }> = {};
  transactions.forEach((tx) => {
    const m = tx.date?.slice(0, 7) || "Unknown";
    if (!monthly[m]) monthly[m] = { credit: 0, debit: 0 };
    if (tx.type === "credit") monthly[m].credit += tx.amount;
    else monthly[m].debit += tx.amount;
  });

  const summaryRows: any[][] = [
    ["Metric", "Amount (Rs.)", "Notes"],
    ["Total Credits", totalCredits, "All income received"],
    ["Total Debits", totalDebits, "All expenses paid"],
    ["Net Balance", balance, balance >= 0 ? "Surplus" : "Deficit"],
    ["Annual Budget", budget, "Set by committee"],
    ["Budget Used %", `${Math.min((totalDebits / budget) * 100, 100).toFixed(1)}%`, totalDebits > budget ? "OVER BUDGET" : "Within budget"],
    [],
    ["Month", "Credits (Rs.)", "Debits (Rs.)"],
  ];

  summaryRows.forEach((r, i) => {
    const row = sum.addRow(r);
    if (i === 0 || i === 7) { applyHeaderRow(row); }
    else if (r.length) {
      row.getCell(1).font = baseFont(true, 11);
      row.getCell(2).font = baseFont(false, 11);
      if (i === 3) {
        row.getCell(2).fill = balance >= 0 ? GREEN_FILL : RED_FILL;
        row.getCell(2).font = baseFont(true, 11, balance >= 0 ? "FF155724" : "FF721C24");
      }
    }
  });

  Object.entries(monthly).sort().forEach(([m, v]) => {
    const row = sum.addRow([m, v.credit, v.debit]);
    row.getCell(2).fill = GREEN_FILL; row.getCell(2).font = baseFont(false, 11, "FF155724");
    row.getCell(3).fill = RED_FILL;   row.getCell(3).font = baseFont(false, 11, "FF721C24");
  });

  autoWidth(sum);
  sum.views = [{ state: "frozen", ySplit: 4 }];

  // ── Dashboard ──
  const dash = wb.addWorksheet("Dashboard");
  addTitleBlock(dash, "FUND DASHBOARD", "Balance Trend & Category Breakdown", 4);
  dash.addRow([]);

  dash.addRow(["Date", "Balance (Rs.)"]);
  applyHeaderRow(dash.getRow(dash.rowCount));
  let rb = 0;
  sorted.forEach((tx) => {
    rb += tx.type === "credit" ? tx.amount : -tx.amount;
    dash.addRow([tx.date, rb]);
  });

  dash.addRow([]);
  dash.addRow(["Category", "Total Spent (Rs.)"]);
  applyHeaderRow(dash.getRow(dash.rowCount));
  const catTotals: Record<string, number> = {};
  transactions.filter(t => t.type === "debit").forEach((t) => {
    catTotals[t.category] = (catTotals[t.category] || 0) + t.amount;
  });
  Object.entries(catTotals).sort((a, b) => b[1] - a[1]).forEach(([cat, amt]) => {
    dash.addRow([cat, amt]);
  });

  autoWidth(dash);
  dash.views = [{ state: "frozen", ySplit: 4 }];

  // ── Insights ──
  const ins = wb.addWorksheet("Insights");
  addTitleBlock(ins, "FUND INSIGHTS", "Auto-generated financial observations", 2);
  ins.addRow([]);

  const topCat = Object.entries(catTotals).sort((a, b) => b[1] - a[1])[0];
  const monthlyArr = Object.entries(monthly).sort();
  let expenseChange = "N/A";
  if (monthlyArr.length >= 2) {
    const prev = monthlyArr[monthlyArr.length - 2][1].debit;
    const curr = monthlyArr[monthlyArr.length - 1][1].debit;
    const pct = prev > 0 ? (((curr - prev) / prev) * 100).toFixed(1) : "N/A";
    expenseChange = `${pct}%`;
  }

  const top5 = Object.entries(catTotals).sort((a, b) => b[1] - a[1]).slice(0, 5);

  const insightRows = [
    ["#", "Insight"],
    ["1", topCat ? `Highest spending category: ${topCat[0]} (Rs. ${topCat[1].toLocaleString("en-IN")})` : "No expense data"],
    ["2", `Expenses changed by ${expenseChange} compared to previous month`],
    ["3", `Net balance is ${balance >= 0 ? "SURPLUS" : "DEFICIT"} of Rs. ${Math.abs(balance).toLocaleString("en-IN")}`],
    ["4", totalDebits > budget ? `Budget EXCEEDED by Rs. ${(totalDebits - budget).toLocaleString("en-IN")}` : `Rs. ${(budget - totalDebits).toLocaleString("en-IN")} remaining in annual budget`],
    ["5", `Total of ${transactions.filter(t => t.status === "Pending").length} transactions pending approval`],
    [],
    ["Rank", "Top 5 Expense Categories", "Amount (Rs.)"],
    ...top5.map(([cat, amt], i) => [i + 1, cat, amt]),
  ];

  insightRows.forEach((r, i) => {
    const row = ins.addRow(r);
    if (i === 0 || i === 7) { applyHeaderRow(row); }
    else if (r.length) {
      row.getCell(1).font = baseFont(true, 11);
      row.getCell(2).font = baseFont(false, 11);
      if (r[2]) row.getCell(3).font = baseFont(false, 11);
    }
  });

  autoWidth(ins);
  ins.views = [{ state: "frozen", ySplit: 4 }];

  addMetadataSheet(wb, generatedBy, transactions.length);

  const buf = await wb.xlsx.writeBuffer();
  saveAs(new Blob([buf]), `Society_Fund_Report_${new Date().toISOString().split("T")[0]}.xlsx`);
}

// ── SOCIETY BUDGET EXPORT ─────────────────────────────────────────────────────

export async function exportBudgetExcel(categories: { name: string; allocated: number; spent: number }[], generatedBy = "Admin") {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Trackify";
  wb.created = new Date();

  // ── Raw Data ──
  const raw = wb.addWorksheet("Raw Data");
  addTitleBlock(raw, "SOCIETY BUDGET REPORT", `Generated: ${new Date().toLocaleDateString("en-IN")}`, 5);
  raw.addRow([]);

  const headers = ["Category", "Allocated (Rs.)", "Spent (Rs.)", "Remaining (Rs.)", "Status"];
  const hRow = raw.addRow(headers);
  applyHeaderRow(hRow);

  categories.forEach((cat) => {
    const remaining = cat.allocated - cat.spent;
    const status = remaining < 0 ? "Overspent" : remaining / cat.allocated < 0.2 ? "Critical" : "Healthy";
    const row = raw.addRow([cat.name, cat.allocated, cat.spent, remaining, status]);

    row.eachCell((c) => { c.font = baseFont(false, 11); c.alignment = { vertical: "middle" }; });

    const remCell = row.getCell(4);
    const stCell  = row.getCell(5);
    if (remaining < 0) {
      remCell.fill = RED_FILL; remCell.font = baseFont(true, 11, "FF721C24");
      stCell.fill  = RED_FILL; stCell.font  = baseFont(true, 11, "FF721C24");
    } else if (status === "Critical") {
      remCell.fill = AMBER_FILL; remCell.font = baseFont(true, 11, "FF856404");
      stCell.fill  = AMBER_FILL; stCell.font  = baseFont(true, 11, "FF856404");
    } else {
      remCell.fill = GREEN_FILL; remCell.font = baseFont(true, 11, "FF155724");
      stCell.fill  = GREEN_FILL; stCell.font  = baseFont(true, 11, "FF155724");
    }
  });

  autoWidth(raw);
  freezeAndFilter(raw, 4);

  // ── Summary ──
  const sum = wb.addWorksheet("Summary");
  addTitleBlock(sum, "BUDGET SUMMARY", "", 3);
  sum.addRow([]);

  const totalAllocated = categories.reduce((s, c) => s + c.allocated, 0);
  const totalSpent     = categories.reduce((s, c) => s + c.spent, 0);
  const totalRemaining = totalAllocated - totalSpent;
  const overspent      = categories.filter(c => c.spent > c.allocated);

  const summaryRows = [
    ["Metric", "Amount (Rs.)", "Notes"],
    ["Total Budget", totalAllocated, "Sum of all allocations"],
    ["Total Spent", totalSpent, "Sum of all expenses"],
    ["Total Remaining", totalRemaining, totalRemaining >= 0 ? "Within budget" : "Over budget"],
    ["Overspent Categories", overspent.length, overspent.map(c => c.name).join(", ") || "None"],
    ["Budget Utilization", `${((totalSpent / totalAllocated) * 100).toFixed(1)}%`, ""],
  ];

  summaryRows.forEach((r, i) => {
    const row = sum.addRow(r);
    if (i === 0) { applyHeaderRow(row); }
    else {
      row.getCell(1).font = baseFont(true, 11);
      row.getCell(2).font = baseFont(false, 11);
      row.getCell(3).font = baseFont(false, 10, "FF888888");
      if (i === 3) {
        row.getCell(2).fill = totalRemaining >= 0 ? GREEN_FILL : RED_FILL;
        row.getCell(2).font = baseFont(true, 11, totalRemaining >= 0 ? "FF155724" : "FF721C24");
      }
    }
  });

  autoWidth(sum);
  sum.views = [{ state: "frozen", ySplit: 4 }];

  // ── Dashboard ──
  const dash = wb.addWorksheet("Dashboard");
  addTitleBlock(dash, "BUDGET DASHBOARD", "Allocation vs Spending", 4);
  dash.addRow([]);

  dash.addRow(["Category", "Allocated (Rs.)", "Spent (Rs.)", "Remaining (Rs.)"]);
  applyHeaderRow(dash.getRow(dash.rowCount));
  categories.forEach((c) => {
    const row = dash.addRow([c.name, c.allocated, c.spent, c.allocated - c.spent]);
    row.getCell(3).fill = c.spent > c.allocated ? RED_FILL : GREEN_FILL;
    row.getCell(4).fill = c.allocated - c.spent < 0 ? RED_FILL : GREEN_FILL;
  });

  autoWidth(dash);
  dash.views = [{ state: "frozen", ySplit: 4 }];

  // ── Insights ──
  const ins = wb.addWorksheet("Insights");
  addTitleBlock(ins, "BUDGET INSIGHTS", "Auto-generated budget observations", 2);
  ins.addRow([]);

  const mostEfficient = categories.filter(c => c.spent <= c.allocated).sort((a, b) => (a.spent / a.allocated) - (b.spent / b.allocated))[0];

  const insightRows = [
    ["#", "Insight"],
    ["1", `${overspent.length} categor${overspent.length === 1 ? "y" : "ies"} exceeded budget: ${overspent.map(c => c.name).join(", ") || "None"}`],
    ["2", mostEfficient ? `Most efficient category: ${mostEfficient.name} (${((mostEfficient.spent / mostEfficient.allocated) * 100).toFixed(1)}% used)` : "No data"],
    ["3", `Overall budget utilization: ${((totalSpent / totalAllocated) * 100).toFixed(1)}%`],
    ["4", `Total unspent budget: Rs. ${Math.max(totalRemaining, 0).toLocaleString("en-IN")}`],
    ["5", `Highest spending category: ${categories.sort((a, b) => b.spent - a.spent)[0]?.name || "N/A"}`],
    [],
    ["Rank", "Category", "Spent (Rs.)", "Status"],
    ...categories.sort((a, b) => b.spent - a.spent).slice(0, 5).map((c, i) => [
      i + 1, c.name, c.spent, c.spent > c.allocated ? "Overspent" : "OK"
    ]),
  ];

  insightRows.forEach((r, i) => {
    const row = ins.addRow(r);
    if (i === 0 || i === 7) { applyHeaderRow(row); }
    else if (r.length) {
      row.getCell(1).font = baseFont(true, 11);
      row.getCell(2).font = baseFont(false, 11);
    }
  });

  autoWidth(ins);
  ins.views = [{ state: "frozen", ySplit: 4 }];

  addMetadataSheet(wb, generatedBy, categories.length);

  const buf = await wb.xlsx.writeBuffer();
  saveAs(new Blob([buf]), `Budget_Report_${new Date().toISOString().split("T")[0]}.xlsx`);
}
